[package]
name = "mitemp"
version = "0.2.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
description = "Read Xiaomi MI Temperature and Humidity Sensor over BLE"
license = "MIT/Apache-2.0"

[dependencies]
btleplug = { version = "0.7", git = "https://github.com/icewind1991/btleplug", branch = "unify-platform-api" }
num_enum = "0.4"

[dev-dependencies]
main_error = "0.1"
env_logger = "0.7"