on: [push, pull_request]

name: Continuous integration

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: "${{ secrets.ATTIC_TOKEN }}"
      - run: nix flake check --keep-going
